# Generated by Django 6.0.8 on 2026-09-23 14:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, max_length=128)),
                ('raw_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('raw_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('direction', models.CharField(blank=True, max_length=255)),
                ('vehicle_type', models.CharField(choices=[('keke', 'Keke Napep'), ('minibus', 'Mini-bus')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('reserved', 'Reserved'), ('expired', 'Expired'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('priority', models.CharField(choices=[('standard', 'Standard'), ('priority', 'Priority')], default='standard', max_length=20)),
                ('pickup_code', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reserved_at', models.DateTimeField(blank=True, null=True)),
                ('reservation_expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_pins', to='drivers.driverprofile')),
                ('corridor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pins', to='geo.corridor')),
                ('junction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pins', to='geo.junction')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to=settings.AUTH_USER_MODEL)),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_pins', to='drivers.driverprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('paged', 'Paged'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], db_index=True, default='paged', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='drivers.driverprofile')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='rides.pin')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PinDriverVisibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distance_meters', models.FloatField()),
                ('rank', models.IntegerField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visibility', to='drivers.driverprofile')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visibility', to='rides.pin')),
            ],
            options={
                'ordering': ['rank'],
                'constraints': [models.UniqueConstraint(fields=('pin', 'driver'), name='unique_pin_driver')],
            },
        ),
    ]
